name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [master, dev]

jobs:
  setup-server:
    name: Setup Backend Server
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: groupher_server_ci
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: 'coderplanets/coderplanets_server'
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: 'server'
      - name: Set up Elixir and OTP
        uses: actions/setup-elixir@v1
        with:
          elixir-version: '1.10.3' # Define the elixir version [required]
          otp-version: '22.3' # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: deps.get
        run: cd server; mix deps.get > /dev/null
      - name: set up test server
        run: cd server; MIX_ENV=ci mix ecto.setup > /dev/null
      - name: seed test data
        run: cd server; MIX_ENV=ci mix run priv/mock/cps_seeds.exs > /dev/null

  setup-front:
    name: Setup Web Front
    runs-on: ubuntu-latest
    needs: setup-server

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Packages
        run: yarn
      - name: Setup config tools
        run: chmod +x ./utils/bin/jq-linux; ./utils/bin/jq-linux -s '.[0] * .[1]' config/config.json config/config.ci.json > /tmp/config.json; cp /tmp/config.json ./config/config.json
      - name: Build Project
        run: npm run build.ci
      - name: Check Bundle Size
        uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: npm run size.check
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
        # run: npm run size.check
      # - name: Run Backend Server
      #   run: cd server; MIX_ENV=ci mix phx.server &
      # - name: Run Tests
      #   run: npm run test:ci
